name: xdev_test
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  bloc_test: ^9.0.1
  cupertino_icons: ^1.0.2
  equatable: ^2.0.3
  file_picker: ^4.2.7
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  freezed_annotation: ^1.0.0
  provider: ^6.0.2
  uuid: ^3.0.5

dev_dependencies:
  async: ^2.8.1
  build_runner: ^2.1.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  freezed: ^1.0.2

flutter:
  uses-material-design: true